### ISSUE TITLE
TypeError when running readme example

### ISSUE THREAD

**Issue by Vvpzz** [click-contrib/click-repl#2]
Hello,

when running the readme example, it fails with :

bla@cpu:/mnt/data/code/python/quick_tests$ python3 test.py repl
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    cli()
  File "/home/bla/.local/lib/python3.4/site-packages/click/core.py", line 700, in `__call__`
    return self.main(*args, **kwargs)
  File "/home/bla/.local/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/bla/.local/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bla/.local/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bla/.local/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/bla/.local/lib/python3.4/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bla/.local/lib/python3.4/site-packages/click_repl/__init__.py", line 66, in cli
    history = History()
TypeError: Can't instantiate abstract class History with abstract methods `__getitem__`, `__iter__`, `__len__`, `append`

I'm using python 3.4.3. I guess my problem might be similar to [this one] (https://github.com/jonathanslenders/python-prompt-toolkit/issues/150).

I understand click-repl is experimental. Do you plan to develop it further?

Thx

**Comment by untitaker** [comment]
Your problem is exactly the same one as far as I can see. It is probably fixed if you install `python-prompt-toolkit` from its git repo.

One tool that I use daily ([todoman](https://github.com/hobarrera/todoman)) has an optional dependency on it. It fits my usecase, so for my purposes the work on click-repl is finished. But I'd certainly like it to be more general-purpose.

**Comment by Vvpzz** [comment]
Thx for the advice. Unfortunately `python-prompt-toolkit` git version won't install on my machine (regular `pip3 install` works fine, but produces the bug above).
I will ask for help there.

**Comment by untitaker** [comment]
I've just looked at the fix, it's something that needs to be fixed in click-repl!

**Comment by Vvpzz** [comment]
Thx for the fix, but now I got the same git installation error as for `python-prompt-toolkit` in my previous comment. Something must be wrong with my setup...

bla@cpu:~$ pip3 install git+https://github.com/click-contrib/click-repl.gitDownloading/unpacking git+https://github.com/click-contrib/click-repl.git
  Cloning https://github.com/click-contrib/click-repl.git to /tmp/pip-daixx9hq-build
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 295, in run_egg_info
    logger.notify('Running setup.py (path:%s) egg_info for package from %s' % (self.setup_py, self.url))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 266, in setup_py
    import setuptools
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/share/python-wheels/setuptools-12.2-py2.py3-none-any.whl/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/share/python-wheels/setuptools-12.2-py2.py3-none-any.whl/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/share/python-wheels/setuptools-12.2-py2.py3-none-any.whl/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

Storing debug log for failure in /home/bla/.pip/pip.log

Any idea? 

Thx

**Comment by untitaker** [comment]
This has got something to do with your packaging tools. I assume you use the
broken debian PIP installation... try installing pip with pip in a virtualenv.
